Fix/snaptoken error
veritrans/veritrans-android pull request #653
Opened 2020-09-03 12:03 UTC by uziwuzzy

1. Fix crash when using snaptoken on credit card
2. Update secure-preferences version to 0.17

2020-09-03 13:30 UTC, askur87 reviewed
LGTM

2020-09-03 15:49 UTC, farhanpahlevi requested changes

2020-09-03 15:49 UTC, farhanpahlevi commented on demo/src/main/java/com/midtrans/demo/DemoOrderReviewActivity.java
> +    private TextInputEditText editName, editEmail, editPhone, editsnap;
camel case?

2020-09-03 15:49 UTC, farhanpahlevi commented on demo/src/main/java/com/midtrans/demo/DemoOrderReviewActivity.java
> +        editsnap = (TextInputEditText)findViewById(R.id.edit_snaptoken);
space after )

2020-09-04 04:45 UTC, femmerling approved these changes
![LGTM](https://user-images.githubusercontent.com/526841/92200347-d5aa2900-eea3-11ea-9ebd-3cc8f66d2d06.gif)

2020-09-04 04:46 UTC, farhanpahlevi approved these changes

2020-09-04 04:55 UTC, merged